--Emily Zeng
--CIS 310-01
--Assignment 9

SELECT *
FROM DETAILRENTAL

CREATE TRIGGER TRG_MEM_BALANCE ON DETAILRENTAL
AFTER	UPDATE
AS
BEGIN

DECLARE @PRIOR_LATEFEE DECIMAL,
		@NEW_LATEFEE   DECIMAL,
		@RENT_FEE	   DECIMAL,
		@RENTAL_MEMBER INT;

IF (EXISTS (SELECT * FROM DELETED) AND EXISTS (SELECT * FROM INSERTED))
	BEGIN
	DECLARE	UPDATE_CURSOR CURSOR FOR
		SELECT	I.RENT_NUM, SUM(@NEW_LATEFEE - @PRIOR_LATEFEE) AS UPDATE_AMOUNT
		FROM	DELETED D INNER JOIN INSERTED I	ON I.RENT_NUM = D.RENT_NUM AND I.VID_NUM = D.VID_NUM
		WHERE	(@NEW_LATEFEE > 0) OR (@NEW_LATEFEE IS NOT NULL)
		GROUP BY I.RENT_NUM

	OPEN	UPDATE_CURSOR
	FETCH	NEXT FROM UPDATE_CURSOR
			INTO @RENT_FEE, @NEW_LATEFEE

	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		UPDATE MEMBERSHIP
		SET	   MEM_BALANCE = @NEW_LATEFEE + @PRIOR_LATEFEE
		WHERE  MEM_NUM = (SELECT	MEM_NUM
						  FROM		RENTAL
						  WHERE		MEM_NUM = @RENTAL_MEMBER)
		FETCH  NEXT FROM UPDATE_CURSOR 
			   INTO @RENT_FEE, @NEW_LATEFEE
		END
		CLOSE UPDATE_CURSOR
		DEALLOCATE UPDATE_CURSOR
	END
END

SELECT	*
FROM	RENTAL
WHERE	RENT_NUM = '1006' OR RENT_NUM = '1007'

UPDATE	DETAILRENTAL
SET		DETAIL_RETURNDATE = DETAIL_RETURNDATE + 3

